# Generated by Django 5.1.1 on 2025-03-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('term_days', models.IntegerField(default=360)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_type', models.CharField(choices=[('maturity', 'Al vencimiento'), ('monthly', 'Mensual')], default='maturity', max_length=20)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('CONTACTED', 'Contactado')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('RESPONDED', 'Respondida'), ('CLOSED', 'Cerrada')], default='PENDING', max_length=20)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_days', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_type', models.CharField(max_length=20)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_notes', models.TextField(blank=True)),
                ('advisor_notes', models.TextField(blank=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_projections', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='client_portal.projectionrequest')),
            ],
        ),
    ]
