# Generated by Django 5.1.1 on 2025-03-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountRequest',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
