# Generated by Django 5.1.1 on 2025-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('CONTACTED', 'Contactado')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
