# Generated by Django 5.1.1 on 2025-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0004_simpleprojection'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleprojection',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='simpleprojection',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='simpleprojection',
            name='net_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='simpleprojection',
            name='payment_type',
            field=models.CharField(choices=[('maturity', 'Al vencimiento'), ('monthly', 'Mensual')], default='maturity', max_length=20),
        ),
        migrations.AddField(
            model_name='simpleprojection',
            name='term_days',
            field=models.IntegerField(default=360),
        ),
        migrations.AlterField(
            model_name='simpleprojection',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
