# Generated by Django 5.1.1 on 2025-02-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('LOAN', 'Solicitud de Préstamo'), ('SAVINGS', 'Apertura Cuenta de Ahorros'), ('CHECKING', 'Apertura Cuenta Corriente'), ('INVESTMENT', 'Asesoría de Inversiones'), ('CARDS', 'Solicitud de Tarjetas'), ('OTHER', 'Otros Servicios')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Cumplida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='blog.client')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
