# Generated by Django 5.1.1 on 2025-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorcode',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='twofactorcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
