# Generated by Django 5.1.1 on 2025-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_twofactorcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsecurityquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
