# Generated by Django 5.1.1 on 2024-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account_delete_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='numberAccount',
            field=models.CharField(default='DEFAULT1', max_length=20),
            preserve_default=False,
        ),
    ]
