# Generated by Django 5.1.1 on 2024-09-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_account_numberaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='numberAccount',
            field=models.CharField(default='DEFAULT1', max_length=20),
        ),
    ]
