# Generated by Django 5.1.1 on 2025-02-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_emailnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
    ]
