# Generated by Django 5.1.1 on 2024-09-21 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_account_numberaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INV', 'Inactive'), ('RP', 'Reported')], default='ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('O', 'OWE'), ('ND', 'NODEBT')], default='ND', max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='blog.client'),
        ),
    ]
