# Generated by Django 5.1.1 on 2025-03-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='net_interest',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='term_days',
        ),
    ]
