# Generated by Django 5.1.1 on 2025-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_projection_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='net_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='payment_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projection',
            name='term_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
