# Generated by Django 5.1.1 on 2024-09-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_account_status_client_status_alter_account_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SV', 'Savings'), ('CK', 'Checking')], default='SV', max_length=2),
        ),
    ]
