# Generated by Django 5.1.1 on 2025-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_projection_final_amount_projection_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='advisor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('CONTACTED', 'Contactado')], default='PENDING', max_length=20),
        ),
    ]
