# Generated by Django 5.1.1 on 2025-03-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_twofactorcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
    ]
