# Generated by Django 5.1.1 on 2024-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_client_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
