# Generated by Django 5.1.1 on 2025-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_client_image_remove_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cardId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
