# Generated by Django 5.1.1 on 2025-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_update_account_types'),
        ('blog', '0010_account_credit_limit_account_management_fee_and_more'),
    ]

    operations = [
    ]
