# Generated by Django 5.1.1 on 2024-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_image_url_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imageSave',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
