# Generated by Django 5.1.1 on 2025-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20250321_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
    ]
