# Generated by Django 5.1.1 on 2025-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_account_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='management_fee',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='virtual_password',
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT de la Empresa'),
        ),
        migrations.AddField(
            model_name='account',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='virtual_key',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Clave Virtual'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS_NORMAL', 'Cuenta de Ahorros Normal'), ('SAVINGS_NOMINA', 'Cuenta Nómina'), ('SAVINGS_AMIGA', 'Cuenta Amiga'), ('CHECKING', 'Cuenta Corriente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite de Crédito'),
        ),
    ]
