# Generated by Django 5.0.4 on 2025-02-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_client_cardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_card_number',
            field=models.CharField(default='0000000000000000', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_cvv',
            field=models.CharField(default='000', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_expiration_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='debit_card_number',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='debit_cvv',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='debit_expiration_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='numberAccount',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
