# Generated by Django 5.0.4 on 2025-02-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_account_credit_card_number_account_credit_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit_card_number',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_cvv',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
    ]
