# Generated by Django 5.0.4 on 2025-02-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_account_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
    ]
