# Generated by Django 5.1.1 on 2025-02-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_loan_options_loan_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ONGOING', 'En Curso'), ('PAID', 'Pagado')], default='PENDING', max_length=10),
        ),
    ]
